# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-11 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instapp', '0005_auto_20181011_0528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='image',
            new_name='post',
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
